# Generated by Django 4.2.7 on 2023-11-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_templates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formtemplate',
            name='fields',
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='field_name_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='field_name_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='formtemplate',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
